export const scoreStateTemplate = [
    {
        p1putt: 0,
        p1total: 0,
        p2putt: 0,
        p2total: 0,
    },
    {
        p1putt: 0,
        p1total: 0,
        p2putt: 0,
        p2total: 0,
    },
    {
        p1putt: 0,
        p1total: 0,
        p2putt: 0,
        p2total: 0,
    },
    {
        p1putt: 0,
        p1total: 0,
        p2putt: 0,
        p2total: 0,
    },
    {
        p1putt: 0,
        p1total: 0,
        p2putt: 0,
        p2total: 0,
    },
    {
        p1putt: 0,
        p1total: 0,
        p2putt: 0,
        p2total: 0,
    },
    {
        p1putt: 0,
        p1total: 0,
        p2putt: 0,
        p2total: 0,
    },
    {
        p1putt: 0,
        p1total: 0,
        p2putt: 0,
        p2total: 0,
    },
    {
        p1putt: 0,
        p1total: 0,
        p2putt: 0,
        p2total: 0,
    },
    {
        p1putt: 0,
        p1total: 0,
        p2putt: 0,
        p2total: 0,
    },
    {
        p1putt: 0,
        p1total: 0,
        p2putt: 0,
        p2total: 0,
    },
    {
        p1putt: 0,
        p1total: 0,
        p2putt: 0,
        p2total: 0,
    },
    {
        p1putt: 0,
        p1total: 0,
        p2putt: 0,
        p2total: 0,
    },
    {
        p1putt: 0,
        p1total: 0,
        p2putt: 0,
        p2total: 0,
    },
    {
        p1putt: 0,
        p1total: 0,
        p2putt: 0,
        p2total: 0,
    },
    {
        p1putt: 0,
        p1total: 0,
        p2putt: 0,
        p2total: 0,
    },
    {
        p1putt: 0,
        p1total: 0,
        p2putt: 0,
        p2total: 0,
    },
    {
        p1putt: 0,
        p1total: 0,
        p2putt: 0,
        p2total: 0,
    },
]