export const scoreStateTemplate = [
    {
        p1putt: '',
        p1total: '',
        p2putt: '',
        p2total: '',
    },
    {
        p1putt: '',
        p1total: '',
        p2putt: '',
        p2total: '',
    },
    {
        p1putt: '',
        p1total: '',
        p2putt: '',
        p2total: '',
    },
    {
        p1putt: '',
        p1total: '',
        p2putt: '',
        p2total: '',
    },
    {
        p1putt: '',
        p1total: '',
        p2putt: '',
        p2total: '',
    },
    {
        p1putt: '',
        p1total: '',
        p2putt: '',
        p2total: '',
    },
    {
        p1putt: '',
        p1total: '',
        p2putt: '',
        p2total: '',
    },
    {
        p1putt: '',
        p1total: '',
        p2putt: '',
        p2total: '',
    },
    {
        p1putt: '',
        p1total: '',
        p2putt: '',
        p2total: '',
    },
    {
        p1putt: '',
        p1total: '',
        p2putt: '',
        p2total: '',
    },
    {
        p1putt: '',
        p1total: '',
        p2putt: '',
        p2total: '',
    },
    {
        p1putt: '',
        p1total: '',
        p2putt: '',
        p2total: '',
    },
    {
        p1putt: '',
        p1total: '',
        p2putt: '',
        p2total: '',
    },
    {
        p1putt: '',
        p1total: '',
        p2putt: '',
        p2total: '',
    },
    {
        p1putt: '',
        p1total: '',
        p2putt: '',
        p2total: '',
    },
    {
        p1putt: '',
        p1total: '',
        p2putt: '',
        p2total: '',
    },
    {
        p1putt: '',
        p1total: '',
        p2putt: '',
        p2total: '',
    },
    {
        p1putt: '',
        p1total: '',
        p2putt: '',
        p2total: '',
    },
];